/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieves 5 posts */
        get: operations["retreve_posts"];
        put?: never;
        post: operations["create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "api/gamble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["gamble"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Gamble: {
            gamble_type: components["schemas"]["GambleTypes"];
        };
        GambleResults: {
            slots?: number[] | null;
        };
        /** @enum {string} */
        GambleTypes: "Slots";
        InfraStemPost: {
            created_at: string;
            goal?: number | null;
            img_urls: string[];
            likes: number;
            location?: null | components["schemas"]["Location"];
            message: string;
            points: number;
            title: string;
            user_id: string;
        };
        Location: {
            coordinates: number[];
            type: string;
        };
        /** @description
         *
         *     Post request (creating a post)
         *
         *      */
        PostDraft: {
            goal?: number | null;
            images: string[];
            location?: null | components["schemas"]["Location"];
            message: string;
            title: string;
        };
        PostResponse: {
            post_id: string;
        };
        Posts: {
            posts: components["schemas"]["InfraStemPost"][];
        };
        /** @description
         *
         *     Get request (Getting a specific or multipple posts)
         *
         *      */
        RetrieveBy: {
            PostId: string;
        } | {
            UserId: string;
        } | "MostLikes" | "MostPoints" | "MostRecent" | "NewToUser";
        RetrievePost: {
            page: number;
            type: components["schemas"]["RetrieveBy"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    retreve_posts: {
        parameters: {
            query: {
                /** @description Type of retrieval */
                type: components["schemas"]["RetrieveBy"];
                /** @description Page number for pagination */
                page: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieves posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Posts"];
                };
            };
            /** @description Unauthorized - missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Creates a post */
        requestBody: {
            content: {
                "multipart/formdata": components["schemas"]["PostDraft"];
            };
        };
        responses: {
            /** @description creates post */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Unauthorized - missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gamble: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generates a list of numbers from 1 to 7 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GambleResults"];
                };
            };
            /** @description Unauthorized - missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
